"use strict";
const assert = require("assert");
const fs = require("fs");
const vm = require("vm");
const path = require("path");
const context = { window: {} };
vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(__dirname,"../data/terrain.js"),"utf8"),context);
vm.runInContext(fs.readFileSync(path.join(__dirname,"../data/scenarios.js"),"utf8"),context);
const scenario = context.window.CROSSROADS_SCENARIOS.mokra;
assert(scenario, "Mokra scenario missing");
assert.equal(scenario.rounds, 6);
assert.equal(scenario.objectives[0].type, "control_group");
assert.equal(scenario.objectives[0].points.length, 3);
assert.equal(scenario.forces.blue.length, 6);
assert.equal(scenario.forces.red.length, 6);
assert(scenario.deployment.zones.blue.subzones.some(zone => zone.id === "forward"));
assert(scenario.deployment.zones.blue.subzones.some(zone => zone.id === "reserve"));
assert(scenario.terrain.filter(item => item.terrainId === "rail_crossing").length === 3);
assert(scenario.terrain.filter(item => item.terrainId === "rail_embankment").length === 4);
for (const item of scenario.terrain) assert(context.window.CROSSROADS_TERRAIN_TYPES[item.terrainId], `Unknown terrain ${item.terrainId}`);
console.log("Mokra scenario: 10/10 passed");
